# /// script
# requires-python = ">=3.14"
# ///
"""Generate many Harbor task instances from one task family by varying surface details (SWE-smith style).

    uv run scripts/generate_instances.py b10 --n 5 --seed 100 --out tasks/generated/
    uv run scripts/generate_instances.py b3  --n 5 --seed 100 --out tasks/generated/

Each instance is a complete, self-contained task directory (instruction, task.toml with `[metadata] generated_from`,
environment with the generated project, solution + alternatives, tests with fixtures, shortcuts incl.
`tamper_store.sh`, and the store-integrity helper). Instance k of a call uses seed `--seed + k`; the same seed always
produces the same instance. Fixtures and expected values are produced by really running the reference solution
through ZenML in a throwaway store (this is the slow part: ~20-40 s per instance), using the interpreter that runs
this script (use `.venv/bin/python scripts/generate_instances.py …` or `uv run --python .venv/bin/python …`).

Families:
  b10  "why did it fail?" on a generated daily-report project: dates, region names, the fault (thousands separator,
       region spelling, timestamp format, negative amounts in parentheses, an extra column), which distractor
       failures precede it, run naming/tag scheme and pipeline name all vary; the grader logic is B10's.
  b3   "stale cache" on a generated nightly-training project: pipeline and step names, output name, data path,
       whether the path is a parameter, which step is the expensive one, and the fixture data all vary; the
       grader logic is B3's.
"""
import argparse
import csv
import json
import os
import random
import shutil
import subprocess
import sys
import tempfile
from datetime import date, timedelta
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
INTEGRITY = ROOT / "shared" / "checks" / "store_integrity.py"


def render(template: str, **kw: Any) -> str:
    """Replace «KEY» markers; braces stay literal so templates can hold Python and JSON."""
    out = template
    for k, v in kw.items():
        out = out.replace(f"«{k}»", str(v))
    assert "«" not in out, f"unrendered marker in template: {out[out.index('«'):][:60]}"
    return out


def write(path: Path, text: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    if executable:
        path.chmod(0o755)


def fresh_env(work: Path) -> dict[str, str]:
    return {**os.environ, "ZENML_CONFIG_PATH": str(work / "zenml"), "ZENML_ANALYTICS_OPT_IN": "false", "ZENML_LOGGING_VERBOSITY": "ERROR"}


def run(cmd: list[str], cwd: Path, env: dict[str, str], check: bool = True) -> subprocess.CompletedProcess:
    proc = subprocess.run(cmd, cwd=cwd, env=env, capture_output=True, text=True, timeout=900)
    if check and proc.returncode != 0:
        raise SystemExit(f"command failed: {' '.join(cmd)}\n{proc.stdout[-2000:]}\n{proc.stderr[-3000:]}")
    return proc


TEST_SH = """#!/usr/bin/env bash
# Verifier entrypoint. Writes reward.json = {"reward": 0|1, ...metrics.json} so Harbor records the extra metrics.
set -uo pipefail
mkdir -p /logs/verifier
cd "${APP_DIR:-/app/«PROJECT»}"
python -m pytest -q /tests -p no:cacheprovider --junitxml=/logs/verifier/junit.xml 2>&1 | tee /logs/verifier/pytest.log
status=${PIPESTATUS[0]}
python - "$status" <<'PY'
import json, sys
from pathlib import Path
reward = 1 if sys.argv[1] == "0" else 0
metrics = {}
try: metrics = json.loads(Path("/logs/verifier/metrics.json").read_text())
except Exception: pass
Path("/logs/verifier/reward.json").write_text(json.dumps({"reward": reward, **metrics}))
PY
exit 0
"""

TASK_TOML = """schema_version = "1.4"

[task]
name = "zenml/«ID»"
version = "0.1.0"
description = "«DESCRIPTION»"

[metadata]
family = "build-and-fix"
tier = "A"
difficulty_estimate = "easy"
zenml_version = "0.96.4"
source = "generated by scripts/generate_instances.py from «FROM»"
generated_from = "«FROM»"
generator_family = "«FAMILY»"
generator_seed = «SEED»
generator_params = «PARAMS»
conditions_supported = ["bare", "skill", "mcp"]

[agent]
timeout_sec = 1800.0
network_mode = "allowlist"
allowed_hosts = ["api.anthropic.com", "api.openai.com", "chatgpt.com"]

[verifier]
timeout_sec = 900.0

[environment]
network_mode = "no-network"
"""


# ----------------------------------------------------------------------------------------------------------------
# b10 family: "why did it fail?"
# ----------------------------------------------------------------------------------------------------------------

REGION_POOLS = [
    ["north", "south", "east", "west"],
    ["emea", "apac", "amer", "latam"],
    ["uk", "de", "fr", "nl"],
    ["central", "coastal", "islands", "highlands"],
    ["retail", "online", "wholesale", "partner"],
]
NAMING = [  # (scheduled prefix, scheduled tag, manual prefix, manual tag)
    ("scheduled", "scheduled", "manual", "manual"),
    ("cron", "cron", "adhoc", "adhoc"),
    ("nightly", "nightly", "manual", "manual"),
    ("job", "scheduled", "run", "manual"),
]
PIPELINE_NAMES = ["sales_summary", "daily_sales", "region_digest", "daily_digest"]  # never a name under shared/projects/ (grade_local.sh would pick that)
EXTRA_COLUMNS = ["currency", "channel", "store_id", "note"]

B10_RUN_PY = '''"""Daily sales report. Run from this directory:

    python run.py --date YYYY-MM-DD [--trigger «S_TRIG»|«M_TRIG»]

Reads data/<date>.csv, types the columns, summarises amounts per region and writes reports/<date>.json.
The cron job runs it every morning with `--trigger «S_TRIG»`; runs started by hand default to `«M_TRIG»`.
"""
import argparse
import json
from typing import Any

import pandas as pd
from zenml import pipeline, step

TS_FORMAT = "%Y-%m-%d %H:%M:%S"
COLUMNS = ["id", "ts", "region", "amount"]
REGIONS = «REGIONS»


@step
def load(date: str) -> pd.DataFrame:
    return pd.read_csv(f"data/{date}.csv")


@step
def parse(raw: pd.DataFrame) -> pd.DataFrame:
    df = raw.copy()
«PARSE_BODY»    return df


@step
def summarise(df: pd.DataFrame) -> dict[str, Any]:
«SUMMARISE_CHECK»    regions = {
        region: {"count": int(g.count()), "total": round(float(g.sum()), 2), "mean": round(float(g.mean()), 2)}
        for region, g in df.groupby("region")["amount"]
    }
    ts = pd.to_datetime(df["ts"])  # the DataFrame may have been round-tripped through the artifact store as text
    return {"rows": int(len(df)), "total": round(float(df["amount"].sum()), 2), "regions": regions,
            "span": [ts.min().strftime(TS_FORMAT), ts.max().strftime(TS_FORMAT)]}


@step
def write_report(summary: dict[str, Any], date: str) -> str:
    path = f"reports/{date}.json"
    with open(path, "w") as f:
        json.dump(summary, f, indent=2)
    return path


@pipeline
def «PIPELINE»(date: str) -> None:
    write_report(summarise(parse(load(date))), date)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", required=True, help="day to process, YYYY-MM-DD (reads data/<date>.csv)")
    ap.add_argument("--trigger", choices=["«S_TRIG»", "«M_TRIG»"], default="«M_TRIG»")
    args = ap.parse_args()
    run_name = f"«S_PREFIX»-{args.date}" if args.trigger == "«S_TRIG»" else f"«M_PREFIX»-{args.date}-{{time}}"
    «PIPELINE».with_options(run_name=run_name, tags=[args.trigger])(date=args.date)
'''

B10_README = """# «PIPELINE»

Summarises one day of sales exports per region and writes `reports/<date>.json`.

```
python run.py --date «EXAMPLE_DATE»                      # by hand: run named «M_PREFIX»-<date>-<time>, tagged `«M_TRIG»`
python run.py --date «EXAMPLE_DATE» --trigger «S_TRIG»  # what cron runs each morning: run named «S_PREFIX»-<date>, tagged `«S_TRIG»`
```

Steps: `load(date)` reads `data/<date>.csv`; `parse` types the columns (`ts` with a strict timestamp format, `amount` as float); `summarise` computes per-region count, total and mean plus the day's time span; `write_report` writes the JSON file and returns its path.

How to tell scheduled runs from manual ones in ZenML: the run name (`«S_PREFIX»-«EXAMPLE_DATE»`) and the tag (`«S_TRIG»`) are both recorded on the pipeline run. `zenml pipeline runs list --tags «S_TRIG» --status failed` filters on them; in Python, `Client().list_pipeline_runs(tags=["«S_TRIG»"])` or `name="startswith:«S_PREFIX»"`. Scheduled run names are fixed per day, so running the same day twice with `--trigger «S_TRIG»` is rejected by ZenML (run names are unique); manual runs carry a `{time}` placeholder and never collide.
"""

B10_INSTRUCTION = """The project in `/app/«PROJECT»` produces a daily sales summary with the ZenML pipeline `«PIPELINE»` (entrypoint: `python run.py --date YYYY-MM-DD`, run from `/app/«PROJECT»`; it reads `data/<date>.csv` and writes `reports/<date>.json`). A cron job runs it every morning for the previous day; those runs are tagged `«S_TRIG»` and named `«S_PREFIX»-<date>`. People also start it by hand now and then. Identify runs by their names and tags, not by their timestamps: this store's history was replayed into it in one sitting, so every run's `created` time is minutes from the others.

The most recent scheduled run failed. Find out which day it was processing and why it failed, fix the code so that the report for that day completes with every row of the day's data counted, and run it: `python run.py --date <that day>`. The report must keep its current contents and format, and the pipeline must keep working for the other days.

Rules: do not edit anything under `data/`; do not delete or modify the existing pipeline runs; leave no pipelines other than `«PIPELINE»` registered in ZenML when you are done. ZenML documentation is available offline at `/opt/zenml-docs/llms-full.txt`.
"""

B10_DOCKERFILE = """FROM zenml-bench/base:0.96.4
# «PROJECT»/ is generated by scripts/generate_instances.py (family b10, seed «SEED»); regenerate, do not edit.
COPY «PROJECT» /app/«PROJECT»
COPY setup_store.sh /opt/setup_store.sh
WORKDIR /app/«PROJECT»
RUN zenml init && bash /opt/setup_store.sh
"""

B10_SETUP_STORE = """#!/usr/bin/env bash
# Produces the pipeline's real run history by running it (never by writing store rows). Generated for seed «SEED».
# Runs at image build (cwd /app/«PROJECT», after `zenml init`) and from scripts/grade_local.sh. Writes a manifest of
# the seeded runs next to the store ($ZENML_CONFIG_PATH) or under /var/lib/zenml-bench (image).
set -uo pipefail
export ZENML_LOGGING_VERBOSITY=ERROR
run() { python run.py "$@" >/dev/null 2>&1 || true; }
rm -rf reports
«HISTORY»
python - <<'PY'
import json, os
from pathlib import Path
from zenml.client import Client
out = Path(os.environ.get("ZENML_CONFIG_PATH") or "/var/lib/zenml-bench") / "seed_runs.json"
out.parent.mkdir(parents=True, exist_ok=True)
runs = [{"id": str(r.id), "name": r.name, "status": str(r.status), "tags": sorted(t.name for t in r.tags),
         "steps": {n: str(s.status) for n, s in r.steps.items()}}
        for r in Client().list_pipeline_runs(sort_by="asc:created", size=50).items]
out.write_text(json.dumps(runs, indent=1))
print(f"seeded {len(runs)} runs -> {out}")
for r in runs: print(f"  {r['name']:<40} {r['status']:<10} {r['steps']}")
PY
"""

B10_GRADER = '''"""Grader for «ID» (generated from B10 why-did-it-fail; family b10, seed «SEED», fault «FAULT»).

The store holds the week's real history (environment/setup_store.sh): distractor failures, completed days, and the
scheduled «TARGET» run that failed in `«FAIL_STEP»` («FAULT_DESC»).

1. A COMPLETED, genuine `«PIPELINE»` run exists whose `load` parameter is date=«TARGET» and whose summary equals
   the reference's for that file (every row counted).
2. The agent's code, run by the grader in a fresh process on two hidden exports (one with the fault in other rows
   and regions, one without it), produces the reference summaries; the runs must be genuine.
3. The seeded runs are untouched. 4. data/«TARGET».csv is byte-identical. 5. Only `«PIPELINE»` is registered.
Env: APP_DIR (default /app/«PROJECT»), FIXTURES_DIR (default /tests/fixtures), SEED_RUNS_PATH.
"""
import hashlib
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pytest
from zenml.client import Client
from zenml.enums import ExecutionStatus

from store_integrity import assert_genuine_run

APP_DIR = Path(os.environ.get("APP_DIR", "/app/«PROJECT»"))
FIXTURES = Path(os.environ.get("FIXTURES_DIR", "/tests/fixtures"))
SEED_RUNS = Path(os.environ.get("SEED_RUNS_PATH") or Path(os.environ.get("ZENML_CONFIG_PATH", "/var/lib/zenml-bench")) / "seed_runs.json")
PIPELINE, TARGET_DATE = "«PIPELINE»", "«TARGET»"
HIDDEN = «HIDDEN»  # date the grader runs -> fixture stem
TOL = 0.011
SEEDED = «SEEDED»  # name prefix -> (run status, {step: status}); produced by setup_store.sh


def all_runs() -> list[Any]:
    return list(Client().list_pipeline_runs(sort_by="asc:created", size=500).items)


def load_date(run: Any) -> str | None:
    step = run.steps.get("load")
    return str(step.config.parameters.get("date")) if step else None


def summary_of(run: Any) -> dict[str, Any] | None:
    step = run.steps.get("summarise")
    if step is None or step.status not in (ExecutionStatus.COMPLETED, ExecutionStatus.CACHED):
        return None
    versions = [v for vs in step.outputs.values() for v in vs]
    return versions[0].load() if versions else None


def same_summary(actual: dict[str, Any] | None, expected: dict[str, Any]) -> bool:
    if not isinstance(actual, dict) or actual.get("rows") != expected["rows"]:
        return False
    if set(actual.get("regions", {})) != set(expected["regions"]):
        return False
    if abs(float(actual.get("total", -1)) - expected["total"]) > TOL:
        return False
    if list(actual.get("span", [])) != list(expected.get("span", [])):
        return False
    for region, exp in expected["regions"].items():
        got = actual["regions"][region]
        if got.get("count") != exp["count"] or any(abs(float(got.get(k, -1)) - exp[k]) > TOL for k in ("total", "mean")):
            return False
    return True


def genuine(run: Any) -> bool:
    try:
        assert_genuine_run(run)
        return True
    except AssertionError:
        return False


def write_metrics(**kv: Any) -> None:
    try:
        p = Path("/logs/verifier/metrics.json"); p.parent.mkdir(parents=True, exist_ok=True)
        old = json.loads(p.read_text()) if p.exists() else {}
        p.write_text(json.dumps(old | kv))
    except OSError:
        pass


@pytest.fixture(scope="module")
def expected() -> dict[str, Any]:
    return json.loads((FIXTURES / "expected.json").read_text())


@pytest.fixture(scope="module")
def runs_before() -> list[Any]:
    runs = all_runs()
    seeded = sum(any(r.name.startswith(p) for p in SEEDED) for r in runs)
    agent = [r for r in runs if not any(r.name.startswith(p) for p in SEEDED)]
    write_metrics(agent_runs=len(agent), agent_failed_runs=sum(r.status == ExecutionStatus.FAILED for r in agent),
                  agent_runs_for_target=sum(load_date(r) == TARGET_DATE for r in agent), seeded_runs_seen=seeded)
    return runs


def test_target_day_completed_with_every_row(runs_before, expected):
    target = [r for r in runs_before if r.status == ExecutionStatus.COMPLETED and load_date(r) == TARGET_DATE]
    assert target, f"no completed {PIPELINE} run with date={TARGET_DATE}; runs: {[(r.name, str(r.status), load_date(r)) for r in runs_before]}"
    good = [r for r in target if same_summary(summary_of(r), expected)]
    assert good, f"no completed {TARGET_DATE} run has the reference summary; got {[summary_of(r) for r in target]}"
    assert any(genuine(r) for r in good), f"the completed {TARGET_DATE} run(s) with the right summary were written by hand, not produced by ZenML"


@pytest.mark.parametrize("hidden_date", list(HIDDEN))
def test_hidden_export_in_fresh_process(hidden_date):
    c = Client()
    for run in all_runs():  # the agent's own runs must not serve cached steps to the grader's run
        for step in run.steps.values():
            c.update_step_run(step.id, cache_expires_at=datetime.now(timezone.utc))
    shutil.copy(FIXTURES / f"{HIDDEN[hidden_date]}.csv", APP_DIR / "data" / f"{hidden_date}.csv")
    seen = {r.id for r in all_runs()}
    proc = subprocess.run([sys.executable, "run.py", "--date", hidden_date], cwd=APP_DIR, capture_output=True, text=True, timeout=600)
    assert proc.returncode == 0, f"entrypoint failed on the hidden export {hidden_date}:\\n{proc.stdout[-1500:]}\\n{proc.stderr[-1500:]}"
    new = [r for r in all_runs() if r.id not in seen]
    assert len(new) == 1, f"expected exactly one new run, found {len(new)}"
    run = new[0]
    assert run.status == ExecutionStatus.COMPLETED and run.pipeline.name == PIPELINE
    assert load_date(run) == hidden_date
    hidden_expected = json.loads((FIXTURES / f"expected_{HIDDEN[hidden_date]}.json").read_text())
    got = summary_of(run)
    assert same_summary(got, hidden_expected), f"summary on the hidden export differs from the reference:\\n got {got}\\n exp {hidden_expected}"
    assert_genuine_run(run)
    assert (APP_DIR / "reports" / f"{hidden_date}.json").exists(), "reports/<date>.json was not written"


def test_seeded_history_untouched(runs_before):
    by_prefix = {p: [r for r in runs_before if r.name.startswith(p)] for p in SEEDED}
    for prefix, (status, steps) in SEEDED.items():
        matches = by_prefix[prefix]
        assert matches, f"seeded run {prefix}* is gone"
        run = matches[0]
        assert str(run.status) == status, f"{run.name}: status {run.status}, seeded as {status}"
        assert {n: str(s.status) for n, s in run.steps.items()} == steps, f"{run.name}: step statuses changed"
    failed = by_prefix["«S_PREFIX»-«TARGET»"][0].steps["«FAIL_STEP»"]
    assert failed.exception_info and "ValueError" in failed.exception_info.source
    if SEED_RUNS.exists():
        seeded_ids = {r["id"] for r in json.loads(SEED_RUNS.read_text())}
        assert seeded_ids <= {str(r.id) for r in runs_before}, "a seeded run was deleted (id missing)"


def test_data_file_unchanged():
    shipped = hashlib.sha256((FIXTURES / f"{TARGET_DATE}.csv").read_bytes()).hexdigest()
    current = hashlib.sha256((APP_DIR / "data" / f"{TARGET_DATE}.csv").read_bytes()).hexdigest()
    assert current == shipped, f"data/{TARGET_DATE}.csv was modified"


def test_collateral():
    assert {p.name for p in Client().list_pipelines(size=50).items} == {PIPELINE}
'''

# One patch script = a bash script that edits run.py in place with a python heredoc; PATCH_OLD must be in the file.
PATCH_SH = """#!/usr/bin/env bash
# «COMMENT»
set -euo pipefail
cd "${APP_DIR:-/app/«PROJECT»}"
python - <<'PY'
from pathlib import Path
p = Path("run.py"); s = p.read_text()
«EDITS»
p.write_text(s)
PY
«AFTER»
"""

B10_TAMPER = """#!/usr/bin/env bash
# Tamper: compute the «TARGET» summary outside the pipeline (pandas, fault handled by hand), save it as an artifact
# by hand, and write a completed `«PIPELINE»` run for that day into the store on the failed run's snapshot (which
# carries date=«TARGET»). The pipeline code is never fixed. Must score 0.
set -euo pipefail
cd "${APP_DIR:-/app/«PROJECT»}"
mkdir -p reports
python - <<'PY'
import json
from datetime import datetime, timezone
from uuid import uuid4
import pandas as pd
from zenml import save_artifact
from zenml.client import Client
from zenml.enums import ExecutionStatus
from zenml.models import PipelineRunRequest, PipelineRunUpdate, StepRunRequest
DATE = "«TARGET»"
TS_FORMAT = "%Y-%m-%d %H:%M:%S"
df = pd.read_csv(f"data/{DATE}.csv")
«CLEAN»
regions = {r: {"count": int(g.count()), "total": round(float(g.sum()), 2), "mean": round(float(g.mean()), 2)} for r, g in df.groupby("region")["amount"]}
summary = {"rows": int(len(df)), "total": round(float(df["amount"].sum()), 2), "regions": regions, "span": [df["ts"].min().strftime(TS_FORMAT), df["ts"].max().strftime(TS_FORMAT)]}
json.dump(summary, open(f"reports/{DATE}.json", "w"), indent=2)
c = Client(); zs = c.zen_store; now = datetime.now(timezone.utc)
failed = c.get_pipeline_run(f"«S_PREFIX»-{DATE}")
raw_av = save_artifact(df, name="raw"); sum_av = save_artifact(summary, name="summary"); path_av = save_artifact(f"reports/{DATE}.json", name="path")
run, _ = zs.get_or_create_run(PipelineRunRequest(name=f"«M_PREFIX»-{DATE}-forged-{uuid4().hex[:6]}", project=c.active_project.id, snapshot=failed.snapshot.id, status=ExecutionStatus.RUNNING, orchestrator_run_id=uuid4().hex, start_time=now, tags=["«M_TRIG»"]))
for name, ins, outs in (("load", {}, {"output": [raw_av.id]}), ("parse", {"raw": [raw_av.id]}, {"output": [raw_av.id]}), ("summarise", {"df": [raw_av.id]}, {"output": [sum_av.id]}), ("write_report", {"summary": [sum_av.id]}, {"output": [path_av.id]})):
    zs.create_run_step(StepRunRequest(name=name, pipeline_run_id=run.id, project=c.active_project.id, status=ExecutionStatus.COMPLETED, start_time=now, end_time=now, inputs=ins, outputs=outs))
zs.update_run(run.id, PipelineRunUpdate(status=ExecutionStatus.COMPLETED))
print("forged", c.get_pipeline_run(run.id).name)
PY
"""

CLEAN_TS = 'df["ts"] = pd.to_datetime(df["ts"].str.replace("/", "-"), format=TS_FORMAT)'
CLEAN_REGION = 'df["region"] = df["region"].str.strip().str.lower()'
# Fault catalogue. Each fault: how the broken parse looks, what the fixed parse looks like, how the data is bent,
# what the tamper script does to clean the frame by hand, and which shortcuts / alternatives make sense.
B10_PARSE_BROKEN = {
    "sep": '    df["ts"] = pd.to_datetime(df["ts"], format=TS_FORMAT)\n    df["region"] = df["region"].str.strip().str.lower()\n    df["amount"] = df["amount"].astype(float)\n',
    "region": '    df["ts"] = pd.to_datetime(df["ts"], format=TS_FORMAT)\n    df["amount"] = df["amount"].astype(float)\n',
    "date_fmt": '    df["ts"] = pd.to_datetime(df["ts"], format=TS_FORMAT)\n    df["region"] = df["region"].str.strip().str.lower()\n    df["amount"] = df["amount"].astype(float)\n',
    "paren_neg": '    df["ts"] = pd.to_datetime(df["ts"], format=TS_FORMAT)\n    df["region"] = df["region"].str.strip().str.lower()\n    df["amount"] = df["amount"].astype(float)\n',
    "new_column": '    if list(df.columns) != COLUMNS:\n        raise ValueError(f"unexpected columns in export: {list(df.columns)}")\n    df["ts"] = pd.to_datetime(df["ts"], format=TS_FORMAT)\n    df["region"] = df["region"].str.strip().str.lower()\n    df["amount"] = df["amount"].astype(float)\n',
}
B10_FIX = {  # (old line, new line) applied to run.py by the reference
    "sep": ('    df["amount"] = df["amount"].astype(float)', '    df["amount"] = df["amount"].astype(str).str.replace(",", "", regex=False).astype(float)'),
    "region": ('    df["amount"] = df["amount"].astype(float)', '    df["region"] = df["region"].str.strip().str.lower()\n    df["amount"] = df["amount"].astype(float)'),
    "date_fmt": ('    df["ts"] = pd.to_datetime(df["ts"], format=TS_FORMAT)', '    df["ts"] = pd.to_datetime(df["ts"].str.replace("/", "-", regex=False), format=TS_FORMAT)'),
    "paren_neg": ('    df["amount"] = df["amount"].astype(float)', '    amount = df["amount"].astype(str)\n    negative = amount.str.startswith("(") & amount.str.endswith(")")\n    df["amount"] = amount.str.strip("()").astype(float) * negative.map({True: -1.0, False: 1.0})'),
    "new_column": ('    if list(df.columns) != COLUMNS:\n        raise ValueError(f"unexpected columns in export: {list(df.columns)}")', '    missing = [c for c in COLUMNS if c not in df.columns]\n    if missing:\n        raise ValueError(f"export is missing columns: {missing}")\n    df = df[COLUMNS]'),
}
B10_ALT = {  # a second valid fix (old, new)
    "sep": ('    return pd.read_csv(f"data/{date}.csv")', '    return pd.read_csv(f"data/{date}.csv", thousands=",")'),
    "region": ('    for region, g in df.groupby("region")["amount"]', '    for region, g in df.assign(region=df["region"].str.strip().str.lower()).groupby("region")["amount"]'),
    "date_fmt": ('    df["ts"] = pd.to_datetime(df["ts"], format=TS_FORMAT)', '    df["ts"] = pd.to_datetime(df["ts"], format="mixed")'),
    "paren_neg": ('    df["amount"] = df["amount"].astype(float)', '    df["amount"] = df["amount"].astype(str).str.replace(r"^\\((.*)\\)$", r"-\\1", regex=True).astype(float)'),
    "new_column": ('    if list(df.columns) != COLUMNS:\n        raise ValueError(f"unexpected columns in export: {list(df.columns)}")', '    df = df[[c for c in COLUMNS]]'),
}
B10_SHORTCUT_PATCHES = {  # name -> (comment, old, new) ; each must complete on the target day yet lose or bend rows
    "sep": {
        "coerce_nan": ("Shortcut: coerce unparseable amounts to NaN. Rows stay but their amounts vanish from totals. Must score 0.", '    df["amount"] = df["amount"].astype(float)', '    df["amount"] = pd.to_numeric(df["amount"], errors="coerce")'),
        "drop_bad_rows": ("Shortcut: drop the rows whose amount does not parse. Must score 0.", '    df["amount"] = df["amount"].astype(float)', '    df["amount"] = pd.to_numeric(df["amount"], errors="coerce")\n    df = df.dropna(subset=["amount"])'),
    },
    "region": {
        "drop_bad_rows": ("Shortcut: keep only rows whose region is spelled exactly as expected. Must score 0.", '    df["amount"] = df["amount"].astype(float)', '    df = df[df["region"].isin(REGIONS)]\n    df["amount"] = df["amount"].astype(float)'),
        "allow_variants": ("Shortcut: add the two misspellings seen in this export to the accepted list; the next export spells them differently. Must score 0.", 'REGIONS = ', 'REGIONS = «VARIANTS» + '),
    },
    "date_fmt": {
        "coerce_nat": ("Shortcut: unparseable timestamps become NaT; the day's time span is then wrong. Must score 0.", '    df["ts"] = pd.to_datetime(df["ts"], format=TS_FORMAT)', '    df["ts"] = pd.to_datetime(df["ts"], format=TS_FORMAT, errors="coerce")'),
        "drop_bad_rows": ("Shortcut: drop rows whose timestamp does not parse. Must score 0.", '    df["ts"] = pd.to_datetime(df["ts"], format=TS_FORMAT)', '    df["ts"] = pd.to_datetime(df["ts"], format=TS_FORMAT, errors="coerce")\n    df = df.dropna(subset=["ts"])'),
    },
    "paren_neg": {
        "coerce_nan": ("Shortcut: coerce unparseable amounts to NaN. Must score 0.", '    df["amount"] = df["amount"].astype(float)', '    df["amount"] = pd.to_numeric(df["amount"], errors="coerce")'),
        "strip_parens": ("Shortcut: strip the parentheses and treat refunds as positive amounts. Totals are wrong. Must score 0.", '    df["amount"] = df["amount"].astype(float)', '    df["amount"] = df["amount"].astype(str).str.strip("()").astype(float)'),
    },
    "new_column": {
        "allow_this_column": ("Shortcut: add this export's extra column to the expected list; the next export adds a different one. Must score 0.", 'COLUMNS = ["id", "ts", "region", "amount"]', 'COLUMNS = ["id", "ts", "region", "amount", "«EXTRA»"]'),
    },
}
B10_FAULT_DESC = {
    "sep": "amounts of 1000 or more written with a thousands separator, e.g. \"1,234.50\"",
    "region": "region names capitalised or padded, e.g. \"West \"",
    "date_fmt": "timestamps written with slashes, e.g. \"2026/09/09 13:17:08\"",
    "paren_neg": "refunds written as amounts in parentheses, e.g. \"(123.45)\"",
    "new_column": "an extra column added to the export",
}
B10_FAIL_STEP = {"sep": "parse", "region": "summarise", "date_fmt": "parse", "paren_neg": "parse", "new_column": "parse"}


def b10_params(seed: int) -> dict[str, Any]:
    rng = random.Random(seed)
    year, month = 2026, rng.randint(2, 11)
    end = date(year, month, rng.randint(9, 27))
    n_days = rng.choice([5, 6])
    days = [(end - timedelta(days=n_days - 1 - i)).isoformat() for i in range(n_days)]
    distractors = {"missing_file": rng.random() < 0.7, "missing_dir": rng.random() < 0.7}
    regions = rng.choice(REGION_POOLS)
    fault = rng.choice(list(B10_FIX))
    naming = rng.choice(NAMING)
    typo_style = rng.choice(["day_31", "swapped", "short"])
    d = end
    typo = {"day_31": f"{d.year}-{d.month:02d}-3{rng.choice('123')}", "swapped": f"{d.year}-{d.day:02d}-{d.month:02d}", "short": f"{d.year}-{d.month}-{d.day}"}[typo_style]
    if typo == d.isoformat():
        typo = f"{d.year}-{d.month:02d}-32"
    extra = rng.choice(EXTRA_COLUMNS)
    hidden_extra = rng.choice([c for c in EXTRA_COLUMNS if c != extra])
    variants = rng.sample([regions[0].capitalize(), regions[1].upper(), regions[2] + " ", " " + regions[3], regions[3].title() + " "], 2)
    hidden_variants = [v for v in [regions[1].capitalize() + " ", regions[0].upper(), " " + regions[2].title()] if v not in variants][:2]
    return {"seed": seed, "days": days, "target": days[-1], "distractors": distractors, "regions": regions, "fault": fault,
            "naming": naming, "pipeline": rng.choice(PIPELINE_NAMES), "typo": typo, "extra": extra, "hidden_extra": hidden_extra,
            "variants": variants, "hidden_variants": hidden_variants, "row_seed": rng.randint(1, 10**6),
            "hidden_dates": [(date.fromisoformat(days[0]) - timedelta(days=k)).isoformat() for k in (9, 10)]}


def b10_rows(p: dict[str, Any], day_iso: str, seed: int, n: int, faulty: bool, extra_column: str | None = None, variants: list[str] | None = None) -> tuple[list[str], list[dict[str, str]]]:
    """Rows for one export. `faulty` bends some rows according to p['fault']."""
    rng = random.Random(seed)
    fault = p["fault"]
    fields = ["id", "ts", "region", "amount"] + ([extra_column] if extra_column else [])
    rows: list[dict[str, str]] = []
    bent = set(rng.sample(range(n), max(3, n // 8))) if faulty else set()
    for i in range(n):
        amount = round(rng.uniform(5, 950), 2)
        hh, mm, ss = rng.randint(8, 19), rng.randint(0, 59), rng.randint(0, 59)
        ts = f"{day_iso} {hh:02d}:{mm:02d}:{ss:02d}"
        region = rng.choice(p["regions"])
        row = {"id": f"{day_iso.replace('-', '')}-{i:03d}", "ts": ts, "region": region, "amount": f"{amount:.2f}"}
        if i in bent:
            if fault == "sep":
                amount = round(rng.uniform(1000, 12000), 2); row["amount"] = f"{amount:,.2f}"
            elif fault == "region":
                row["region"] = rng.choice(variants or p["variants"])
            elif fault == "date_fmt":
                row["ts"] = ts.replace("-", "/")
            elif fault == "paren_neg":
                row["amount"] = f"({amount:.2f})"
        if extra_column:
            row[extra_column] = rng.choice(["EUR", "web", "S1", "n/a"])
        rows.append(row)
    if faulty and fault == "date_fmt":  # make sure a bent row carries the day's earliest timestamp, so coercing to NaT changes the span
        first = min(range(n), key=lambda i: rows[i]["ts"].replace("/", "-"))
        rows[first]["ts"] = rows[first]["ts"].replace("-", "/")
    return fields, rows


def write_csv(path: Path, fields: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, quoting=csv.QUOTE_MINIMAL)
        w.writeheader(); w.writerows(rows)


def b10_project(p: dict[str, Any], dst: Path) -> None:
    """Write the generated project (run.py, README, data/) into dst."""
    fault = p["fault"]
    s_prefix, s_tag, m_prefix, m_tag = p["naming"]
    summarise_check = ""
    if fault == "region":
        summarise_check = '    bad = sorted(set(df["region"]) - set(REGIONS))\n    if bad:\n        raise ValueError(f"{int(df[\'region\'].isin(bad).sum())} of {len(df)} rows have a region outside {REGIONS}: {bad}")\n'
    write(dst / "run.py", render(B10_RUN_PY, S_TRIG=s_tag, M_TRIG=m_tag, S_PREFIX=s_prefix, M_PREFIX=m_prefix, PIPELINE=p["pipeline"],
                                 REGIONS=json.dumps(p["regions"]), PARSE_BODY=B10_PARSE_BROKEN[fault], SUMMARISE_CHECK=summarise_check))
    write(dst / "README.md", render(B10_README, PIPELINE=p["pipeline"], S_TRIG=s_tag, M_TRIG=m_tag, S_PREFIX=s_prefix, M_PREFIX=m_prefix, EXAMPLE_DATE=p["days"][-2]))
    rs = p["row_seed"]
    on_disk = [d for d in p["days"] if not (p["distractors"]["missing_file"] and d == p["days"][0])]
    for k, d in enumerate(on_disk):
        faulty = d == p["target"]
        fields, rows = b10_rows(p, d, rs + k, random.Random(rs + k).randint(30, 60), faulty, extra_column=p["extra"] if (faulty and fault == "new_column") else None)
        write_csv(dst / "data" / f"{d}.csv", fields, rows)


def b10_fixtures(p: dict[str, Any], dst: Path) -> None:
    rs = p["row_seed"] + 500
    h_fault, h_plain = p["hidden_dates"]
    fields, rows = b10_rows(p, h_fault, rs, 55, True, extra_column=p["hidden_extra"] if p["fault"] == "new_column" else None, variants=p["hidden_variants"])
    write_csv(dst / "hidden.csv", fields, rows)
    fields, rows = b10_rows(p, h_plain, rs + 1, 37, False)
    write_csv(dst / "hidden_plain.csv", fields, rows)


def b10_history(p: dict[str, Any]) -> tuple[str, dict[str, tuple[str, dict[str, str]]]]:
    """setup_store.sh body and the SEEDED map the grader checks."""
    s_prefix, s_tag, m_prefix, m_tag = p["naming"]
    ok = {"load": "completed", "parse": "completed", "summarise": "completed", "write_report": "completed"}
    lines, seeded = [], {}
    dir_made = False
    for i, d in enumerate(p["days"]):
        name = f"{s_prefix}-{d}"
        if p["distractors"]["missing_file"] and i == 0:
            lines.append(f"run --date {d} --trigger {s_tag}   # no data/{d}.csv was delivered: FileNotFoundError in `load`")
            seeded[name] = ("failed", {"load": "failed"})
            continue
        if p["distractors"]["missing_dir"] and not dir_made and d != p["target"]:
            lines.append(f"run --date {d} --trigger {s_tag}   # reports/ did not exist yet: FileNotFoundError in `write_report`")
            lines.append("mkdir -p reports                            # ...which someone fixed by hand the same day")
            seeded[name] = ("failed", {"load": "completed", "parse": "completed", "summarise": "completed", "write_report": "failed"})
            dir_made = True
            continue
        if not dir_made:
            lines.append("mkdir -p reports"); dir_made = True
        if d == p["target"]:
            fail_step = B10_FAIL_STEP[p["fault"]]
            steps = {"load": "completed", "parse": "failed"} if fail_step == "parse" else {"load": "completed", "parse": "completed", "summarise": "failed"}
            lines.append(f"run --date {d} --trigger {s_tag}   # the real fault ({p['fault']}): ValueError in `{fail_step}`")
            seeded[name] = ("failed", steps)
        else:
            lines.append(f"run --date {d} --trigger {s_tag}   # completed")
            seeded[name] = ("completed", ok)
    lines.append(f"run --date {p['typo']}                       # someone's typo, started by hand after the failure: FileNotFoundError in `load`")
    seeded[f"{m_prefix}-{p['typo']}"] = ("failed", {"load": "failed"})
    return "\n".join(lines), seeded


def patch_script(project: str, comment: str, edits: list[tuple[str, str]], after: str = "") -> str:
    body = "\n".join(f"old = {old!r}; assert old in s, old\ns = s.replace(old, {new!r}, 1)" for old, new in edits)
    return render(PATCH_SH, COMMENT=comment, PROJECT=project, EDITS=body, AFTER=after)


def b10_instance(seed: int, out: Path, python: str) -> Path:
    p = b10_params(seed)
    fault, project, pipeline, target = p["fault"], p["pipeline"], p["pipeline"], p["target"]
    s_prefix, s_tag, m_prefix, m_tag = p["naming"]
    iid = f"b10-gen-{seed:04d}"
    task = out / iid
    if task.exists():
        shutil.rmtree(task)
    env_dir, sol, tests = task / "environment", task / "solution", task / "tests"
    b10_project(p, env_dir / project)
    b10_fixtures(p, tests / "fixtures")
    shutil.copy(env_dir / project / "data" / f"{target}.csv", tests / "fixtures" / f"{target}.csv")
    history, seeded = b10_history(p)
    write(env_dir / "setup_store.sh", render(B10_SETUP_STORE, SEED=seed, PROJECT=project, HISTORY=history), executable=True)
    write(env_dir / "Dockerfile", render(B10_DOCKERFILE, SEED=seed, PROJECT=project))
    write(task / "instruction.md", render(B10_INSTRUCTION, PROJECT=project, PIPELINE=pipeline, S_TRIG=s_tag, S_PREFIX=s_prefix))
    desc = f"Generated B10 instance (fault: {B10_FAULT_DESC[fault]}). The most recent scheduled {pipeline} run failed; find the day and the cause in the ZenML store, fix it, produce the report."
    write(task / "task.toml", render(TASK_TOML, ID=iid, DESCRIPTION=desc, FROM="b10-why-did-it-fail", FAMILY="b10", SEED=seed,
                                     PARAMS=json.dumps({"fault": fault, "target": target, "pipeline": pipeline, "naming": list(p["naming"]), "regions": p["regions"], "distractors": p["distractors"]})))
    # solution + alternatives
    run_target = f"python run.py --date {target}"
    write(sol / "solve.sh", patch_script(project, f"Reference: the {target} export has {B10_FAULT_DESC[fault]}. Fix `parse`, then produce the missing report.", [B10_FIX[fault]], run_target), executable=True)
    write(sol / "alternatives" / "other_fix.sh", patch_script(project, "Alternative: a second valid fix for the same fault.", [B10_ALT[fault]], run_target), executable=True)
    ref_head = 'HERE="$(cd "$(dirname "$0")" && pwd)"\nREF="$HERE/reference.sh"; [ -f "$REF" ] || REF="$HERE/../solve.sh"\nbash "$REF"\ncd "${APP_DIR:-/app/' + project + '}"\n'
    write(sol / "alternatives" / "solve_then_run_twice.sh", "#!/usr/bin/env bash\n# Regression for the shared store: apply the reference, then run the fixed pipeline twice more.\nset -euo pipefail\n" + ref_head + f"python run.py --date {target} && python run.py --date {p['days'][-2]}\n", executable=True)
    write(sol / "alternatives" / "solve_debug_then_revert.sh", "#!/usr/bin/env bash\n# Regression: apply the reference, run, change the summary temporarily (a debug experiment), run, revert, run.\nset -euo pipefail\n" + ref_head + f"sed -i.bak 's/round(float(g.mean()), 2)/round(float(g.mean()), 1)/' run.py && python run.py --date {target}\nmv run.py.bak run.py && python run.py --date {target}\n", executable=True)
    # tests
    write(tests / "test.sh", render(TEST_SH, PROJECT=project), executable=True)
    shutil.copy(INTEGRITY, tests / "store_integrity.py")
    hidden = {p["hidden_dates"][0]: "hidden", p["hidden_dates"][1]: "hidden_plain"}
    write(tests / f"test_{iid.replace('-', '_')}.py", render(B10_GRADER, ID=iid, SEED=seed, FAULT=fault, TARGET=target, FAIL_STEP=B10_FAIL_STEP[fault], FAULT_DESC=B10_FAULT_DESC[fault],
                                                              PIPELINE=pipeline, PROJECT=project, HIDDEN=json.dumps(hidden), SEEDED=repr({k: (v[0], v[1]) for k, v in seeded.items()}), S_PREFIX=s_prefix))
    # shortcuts
    sc = tests / "shortcuts"
    for name, (comment, old, new) in B10_SHORTCUT_PATCHES[fault].items():
        new = new.replace("«VARIANTS»", json.dumps(p["variants"])).replace("«EXTRA»", p["extra"])
        write(sc / f"{name}.sh", patch_script(project, comment, [(old, new)], run_target), executable=True)
    write(sc / "run_yesterday.sh", f"#!/usr/bin/env bash\n# Shortcut: no diagnosis; re-run the pipeline for the day that last worked. Must score 0.\nset -euo pipefail\ncd \"${{APP_DIR:-/app/{project}}}\"\npython run.py --date {p['days'][-2]}\n", executable=True)
    write(sc / "fix_distractor.sh", patch_script(project, "Shortcut: diagnose the most recent failed run (the manual typo) and make the loader fall back to the latest export. Completes, for the wrong day. Must score 0.",
                                                 [('    return pd.read_csv(f"data/{date}.csv")', '    path = Path(f"data/{date}.csv")\n    if not path.exists():\n        path = sorted(Path("data").glob("*.csv"))[-2]\n    return pd.read_csv(path)'), ("import pandas as pd", "from pathlib import Path\n\nimport pandas as pd")], f"python run.py --date {p['typo']}"), executable=True)
    clean = {"sep": f'{CLEAN_TS}\n{CLEAN_REGION}\ndf["amount"] = df["amount"].astype(str).str.replace(",", "", regex=False).astype(float)',
             "region": f'{CLEAN_TS}\n{CLEAN_REGION}\ndf["amount"] = df["amount"].astype(float)',
             "date_fmt": f'{CLEAN_TS}\n{CLEAN_REGION}\ndf["amount"] = df["amount"].astype(float)',
             "paren_neg": f'{CLEAN_TS}\n{CLEAN_REGION}\na = df["amount"].astype(str); neg = a.str.startswith("("); df["amount"] = a.str.strip("()").astype(float) * neg.map({{True: -1.0, False: 1.0}})',
             "new_column": f'df = df[["id", "ts", "region", "amount"]]\n{CLEAN_TS}\n{CLEAN_REGION}\ndf["amount"] = df["amount"].astype(float)'}[fault]
    write(sc / "tamper_store.sh", render(B10_TAMPER, TARGET=target, PIPELINE=pipeline, PROJECT=project, CLEAN=clean, S_PREFIX=s_prefix, M_PREFIX=m_prefix, M_TRIG=m_tag), executable=True)
    write(sc / "edit_csv.sh", f"#!/usr/bin/env bash\n# Shortcut: fix the data instead of the code. Must score 0 (data/{target}.csv must be byte-identical).\nset -euo pipefail\ncd \"${{APP_DIR:-/app/{project}}}\"\npython - <<'PY'\nimport pandas as pd\nTS_FORMAT = \"%Y-%m-%d %H:%M:%S\"\ndf = pd.read_csv(\"data/{target}.csv\")\n{clean}\ndf[\"ts\"] = df[\"ts\"].dt.strftime(TS_FORMAT)\ndf.to_csv(\"data/{target}.csv\", index=False)\nPY\n{run_target}\n", executable=True)
    # expected values: run the unfixed project (must fail on the target day), then the reference, through ZenML
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp); app = work / "app"; shutil.copytree(env_dir / project, app)
        env = fresh_env(work); env["APP_DIR"] = str(app)
        run(["zenml", "init"], app, env)
        (app / "reports").mkdir()
        broken = run([python, "run.py", "--date", target], app, env, check=False)
        assert broken.returncode != 0, f"seed {seed}: the unfixed project completed on {target}; the fault did not bite"
        assert "ValueError" in broken.stderr + broken.stdout, f"seed {seed}: unexpected failure mode:\n{broken.stderr[-800:]}"
        run(["bash", str(sol / "solve.sh")], app, env)
        expected = {}
        for d, stem in ((target, "expected"), (p["hidden_dates"][0], "expected_hidden"), (p["hidden_dates"][1], "expected_hidden_plain")):
            if d != target:
                shutil.copy(tests / "fixtures" / f"{hidden[d]}.csv", app / "data" / f"{d}.csv")
                run([python, "run.py", "--date", d], app, env)
            expected[stem] = json.loads((app / "reports" / f"{d}.json").read_text())
        for stem, value in expected.items():
            write(tests / "fixtures" / f"{stem}.json", json.dumps(value, indent=1))
    print(f"wrote {task.relative_to(ROOT)}  fault={fault} target={target} pipeline={pipeline} naming={s_prefix}/{s_tag} rows={expected['expected']['rows']}")
    return task


# ----------------------------------------------------------------------------------------------------------------
# b3 family: stale cache
# ----------------------------------------------------------------------------------------------------------------

B3_NAMES = {
    "pipeline": ["nightly_training", "model_refresh", "daily_fit", "train_nightly", "overnight_model"],
    "loader": ["load_data", "read_dataset", "ingest", "load_rows"],
    "trainer": ["train", "fit_model", "fit", "train_model"],
    "evaluator": ["evaluate", "score_model", "assess", "validate_model"],
    "score": ["score", "accuracy", "metric", "val_accuracy"],
    "data": ["data/train.csv", "data/rows.csv", "data/latest.csv", "data/training_set.csv"],
    "label": ["label", "target", "y", "outcome"],
}

B3_RUN_PY = '''"""«PIPELINE»: trains a small model every night. Run from this directory: `python run.py`."""
import time
from typing import Annotated

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from zenml import pipeline, step

DATA_PATH = "«DATA»"
LABEL = "«LABEL»"


@step
def «LOADER»(«LOADER_SIG») -> pd.DataFrame:
    return pd.read_csv(«LOADER_PATH»)


@step
def «TRAINER»(df: pd.DataFrame) -> LogisticRegression:
«TRAIN_SLEEP»    x, y = df.drop(columns=LABEL), df[LABEL]
    return LogisticRegression(max_iter=1000).fit(x, y)


@step
def «EVALUATOR»(model: LogisticRegression, df: pd.DataFrame) -> Annotated[float, "«SCORE»"]:
«EVAL_SLEEP»    x, y = df.drop(columns=LABEL), df[LABEL]
    _, x_test, _, y_test = train_test_split(x, y, test_size=«TEST_SIZE», random_state=«SPLIT_SEED»)
    score = float(model.score(x_test, y_test))
    print(f"«SCORE»={score:.4f}")
    return score


@pipeline
def «PIPELINE»(«PIPE_SIG») -> None:
    df = «LOADER»(«LOADER_CALL»)
    model = «TRAINER»(df=df)
    «EVALUATOR»(model=model, df=df)


if __name__ == "__main__":
    «PIPELINE»()
'''

B3_INSTRUCTION = """The project in `/app/«PROJECT»` trains a small model every night from `«DATA»` using the ZenML pipeline `«PIPELINE»` (entrypoint: `python run.py`, run from `/app/«PROJECT»`).

Yesterday the data file was replaced with new rows at the same path, but the pipeline kept reporting the old evaluation «SCORE» because ZenML served cached results.

Fix the project so that:

1. when `«DATA»` changes, the steps that depend on it run again and the reported «SCORE» reflects the new data;
2. when the file has not changed, an unchanged rerun still reuses cached results for the expensive `«EXPENSIVE»` step;
3. the entrypoint, the pipeline name `«PIPELINE»`, and the step name `«EXPENSIVE»` stay the same, and the evaluation «SCORE» is still logged as the `«SCORE»` output of the `«EVALUATOR»` step.

Do not disable caching for the whole pipeline. You can run the pipeline as many times as you like, but leave no other pipelines registered in ZenML when you are done. ZenML documentation is available offline at `/opt/zenml-docs/llms-full.txt`.
"""

B3_DOCKERFILE = """FROM zenml-bench/base:0.96.4
# «PROJECT»/ is generated by scripts/generate_instances.py (family b3, seed «SEED»); regenerate, do not edit.
COPY «PROJECT» /app/«PROJECT»
WORKDIR /app/«PROJECT»
RUN zenml init
"""

B3_GRADER = '''"""Grader for «ID» (generated from B3 stale-cache; family b3, seed «SEED»). Runs the agent's entrypoint against fresh
fixtures a, a, b, b, c and reads the store. Cache assertions are on the expensive step `«EXPENSIVE»` only; every graded
run must be genuine (store_integrity). Env: APP_DIR (default /app/«PROJECT»), FIXTURES_DIR (default /tests/fixtures).
"""
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest
from zenml.client import Client
from zenml.enums import ExecutionStatus

from store_integrity import assert_genuine_run

APP_DIR = Path(os.environ.get("APP_DIR", "/app/«PROJECT»"))
FIXTURES = Path(os.environ.get("FIXTURES_DIR", "/tests/fixtures"))
PIPELINE, EXPENSIVE, EVALUATOR, SCORE, DATA = "«PIPELINE»", "«EXPENSIVE»", "«EVALUATOR»", "«SCORE»", "«DATA»"
TOL = 1e-4
SEQUENCE = ["a", "a", "b", "b", "c"]


def run_entrypoint() -> Any:
    seen = {r.id for r in Client().list_pipeline_runs(size=200).items}
    proc = subprocess.run([sys.executable, "run.py"], cwd=APP_DIR, capture_output=True, text=True, timeout=600)
    assert proc.returncode == 0, f"entrypoint failed:\\n{proc.stdout[-2000:]}\\n{proc.stderr[-2000:]}"
    new = [r for r in Client().list_pipeline_runs(sort_by="desc:created", size=5).items if r.id not in seen]
    assert len(new) == 1, f"expected exactly one new run, found {len(new)}"
    return new[0]


def score_of(run: Any) -> float:
    return float(run.steps[EVALUATOR].outputs[SCORE][0].load())


def status(run: Any, step: str) -> ExecutionStatus:
    return run.steps[step].status


@pytest.fixture(scope="module")
def runs() -> list[Any]:
    out = []
    for name in SEQUENCE:
        shutil.copy(FIXTURES / f"{name}.csv", APP_DIR / DATA)
        out.append(run_entrypoint())
    return out


@pytest.fixture(scope="module")
def expected() -> dict[str, float]:
    return json.loads((FIXTURES / "expected.json").read_text())


def test_all_runs_completed(runs):
    assert [r.status for r in runs] == [ExecutionStatus.COMPLETED] * len(SEQUENCE)
    assert all(r.pipeline.name == PIPELINE for r in runs)


def test_scores_track_the_data(runs, expected):
    got = [score_of(r) for r in runs]
    want = [expected[n] for n in SEQUENCE]
    assert got == pytest.approx(want, abs=TOL), f"scores {got} != expected {want}"


def test_expensive_step_reruns_when_data_changes(runs):
    assert status(runs[2], EXPENSIVE) == ExecutionStatus.COMPLETED  # a -> b
    assert status(runs[4], EXPENSIVE) == ExecutionStatus.COMPLETED  # b -> c


def test_expensive_step_is_cached_on_unchanged_rerun(runs):
    assert status(runs[1], EXPENSIVE) == ExecutionStatus.CACHED  # a again
    assert status(runs[3], EXPENSIVE) == ExecutionStatus.CACHED  # b again


def test_runs_are_genuine(runs):
    for r in runs:
        assert_genuine_run(r)


def test_collateral(runs):
    names = {p.name for p in Client().list_pipelines(size=50).items}
    assert names == {PIPELINE}, f"unexpected pipelines registered: {names}"
    assert SCORE in runs[-1].steps[EVALUATOR].outputs
'''

B3_TAMPER = """#!/usr/bin/env bash
# Tamper: disable caching everywhere (so scores track the data), then after each run open the store's SQLite file
# and mark `«EXPENSIVE»` as "cached" whenever the data file is unchanged since the previous run. Must score 0.
set -euo pipefail
cd "${APP_DIR:-/app/«PROJECT»}"
python - <<'PY'
from pathlib import Path
p = Path("run.py"); s = p.read_text()
for name in ("«LOADER»", "«TRAINER»", "«EVALUATOR»"):
    s = s.replace(f"@step\\ndef {name}", f"@step(enable_cache=False)\\ndef {name}")
old = 'if __name__ == "__main__":\\n    «PIPELINE»()\\n'
assert old in s
s = s.replace(old, '''if __name__ == "__main__":
    import hashlib, sqlite3
    from pathlib import Path
    from zenml.client import Client
    run = «PIPELINE»()
    digest = hashlib.sha256(Path(DATA_PATH).read_bytes()).hexdigest()
    marker = Path(".last_digest")
    if marker.exists() and marker.read_text() == digest:
        con = sqlite3.connect(Client().zen_store.config.url.removeprefix("sqlite:///"))
        con.execute("update step_run set status='cached' where name='«EXPENSIVE»' and pipeline_run_id=?", (run.id.hex,))
        con.commit(); con.close()
    marker.write_text(digest)
''')
p.write_text(s)
PY
"""


def b3_params(seed: int) -> dict[str, Any]:
    rng = random.Random(seed)
    names = {k: rng.choice(v) for k, v in B3_NAMES.items()}
    return {"seed": seed, **names, "path_is_param": rng.random() < 0.5, "expensive": rng.choice(["trainer", "trainer", "evaluator"]),
            "test_size": rng.choice([0.25, 0.3, 0.35]), "split_seed": rng.randint(0, 9), "n_samples": rng.choice([500, 600, 800]),
            "n_features": rng.choice([6, 8, 10]), "data_seeds": [rng.randint(0, 10**4) for _ in range(3)],
            "noise": sorted(rng.sample([0.01, 0.02, 0.05, 0.1, 0.15, 0.2, 0.3, 0.35], 3)), "project": rng.choice(["nightly_job", "training_job", "overnight", "modeljob"])}  # never a name under shared/projects/


def b3_run_py(p: dict[str, Any]) -> str:
    loader_sig, loader_path, pipe_sig, loader_call = ("path: str", "path", "path: str = DATA_PATH", "path=path") if p["path_is_param"] else ("", "DATA_PATH", "", "")
    sleep = "    time.sleep(3)  # stand-in for real work\n"
    return render(B3_RUN_PY, PIPELINE=p["pipeline"], DATA=p["data"], LABEL=p["label"], LOADER=p["loader"], LOADER_SIG=loader_sig, LOADER_PATH=loader_path,
                  TRAINER=p["trainer"], EVALUATOR=p["evaluator"], SCORE=p["score"], TEST_SIZE=p["test_size"], SPLIT_SEED=p["split_seed"],
                  PIPE_SIG=pipe_sig, LOADER_CALL=loader_call, TRAIN_SLEEP=sleep if p["expensive"] == "trainer" else "", EVAL_SLEEP=sleep if p["expensive"] == "evaluator" else "")


def b3_fixture(p: dict[str, Any], k: int, path: Path) -> None:
    import pandas as pd  # the generator runs under the project venv
    from sklearn.datasets import make_classification
    x, y = make_classification(n_samples=p["n_samples"], n_features=p["n_features"], n_informative=max(3, p["n_features"] - 3), flip_y=p["noise"][k], random_state=p["data_seeds"][k])
    df = pd.DataFrame(x, columns=[f"f{i}" for i in range(x.shape[1])]); df[p["label"]] = y
    path.parent.mkdir(parents=True, exist_ok=True); df.to_csv(path, index=False)


def b3_scores(p: dict[str, Any], fixtures: Path) -> dict[str, float]:
    """Scores the generated project would print for each fixture (same model and split as run.py), computed in-process."""
    import pandas as pd
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import train_test_split
    out = {}
    for name in "abc":
        df = pd.read_csv(fixtures / f"{name}.csv")
        x, y = df.drop(columns=p["label"]), df[p["label"]]
        model = LogisticRegression(max_iter=1000).fit(x, y)
        _, x_test, _, y_test = train_test_split(x, y, test_size=p["test_size"], random_state=p["split_seed"])
        out[name] = float(model.score(x_test, y_test))
    return out


def b3_instance(seed: int, out: Path, python: str) -> Path:
    p = b3_params(seed)
    project, pipeline, loader, trainer, evaluator, score, data = p["project"], p["pipeline"], p["loader"], p["trainer"], p["evaluator"], p["score"], p["data"]
    expensive = p[p["expensive"]]
    iid = f"b3-gen-{seed:04d}"
    task = out / iid
    if task.exists():
        shutil.rmtree(task)
    env_dir, sol, tests = task / "environment", task / "solution", task / "tests"
    write(env_dir / project / "run.py", b3_run_py(p))
    for attempt in range(20):  # the three fixtures must score distinctly (a repeated score would hide a stale cache); redraw data seeds until they do
        for k, name in enumerate("abc"):
            b3_fixture(p, k, tests / "fixtures" / f"{name}.csv")
        if len({round(v, 3) for v in b3_scores(p, tests / "fixtures").values()}) == 3:
            break
        p["data_seeds"] = [d + 7919 * (attempt + 1) for d in p["data_seeds"]]
    else:
        raise SystemExit(f"seed {seed}: no distinct fixture scores after 20 redraws")
    (env_dir / project / data).parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(tests / "fixtures" / "a.csv", env_dir / project / data)
    write(env_dir / "Dockerfile", render(B3_DOCKERFILE, SEED=seed, PROJECT=project))
    write(task / "instruction.md", render(B3_INSTRUCTION, PROJECT=project, DATA=data, PIPELINE=pipeline, SCORE=score, EXPENSIVE=expensive, EVALUATOR=evaluator))
    write(task / "task.toml", render(TASK_TOML, ID=iid, DESCRIPTION=f"Generated B3 instance: the {pipeline} pipeline serves stale cached results after {data} is replaced; fix caching without disabling it for the expensive `{expensive}` step.",
                                     FROM="b3-stale-cache", FAMILY="b3", SEED=seed, PARAMS=json.dumps({k: p[k] for k in ("pipeline", "loader", "trainer", "evaluator", "score", "data", "path_is_param", "expensive")})))
    loader_def = f"def {loader}(path: str)" if p["path_is_param"] else f"def {loader}()"
    # reference: an uncached content-hash step feeding the loader
    if p["path_is_param"]:
        fix = [(f"@step\n{loader_def} -> pd.DataFrame:", f"import hashlib\nfrom pathlib import Path\n\n\n@step(enable_cache=False)\ndef content_hash(path: str) -> str:\n    return hashlib.sha256(Path(path).read_bytes()).hexdigest()\n\n\n@step\ndef {loader}(path: str, digest: str) -> pd.DataFrame:"),
               (f"df = {loader}(path=path)", f"df = {loader}(path=path, digest=content_hash(path=path))")]
    else:
        fix = [(f"@step\n{loader_def} -> pd.DataFrame:", f"import hashlib\nfrom pathlib import Path\n\n\n@step(enable_cache=False)\ndef content_hash() -> str:\n    return hashlib.sha256(Path(DATA_PATH).read_bytes()).hexdigest()\n\n\n@step\ndef {loader}(digest: str) -> pd.DataFrame:"),
               (f"df = {loader}()", f"df = {loader}(digest=content_hash())")]
    write(sol / "solve.sh", patch_script(project, "Reference: an uncached content-hash step whose output feeds the loader; the digest hashes by content, so the loader's cache key follows the file.", fix), executable=True)
    write(sol / "alternatives" / "file_dependencies.sh", patch_script(project, "Alternative: CachePolicy(file_dependencies=[DATA_PATH]) on the loader.",
          [("from zenml import pipeline, step", "from zenml import pipeline, step\nfrom zenml.config import CachePolicy"), (f"@step\n{loader_def}", f"@step(cache_policy=CachePolicy(file_dependencies=[DATA_PATH]))\n{loader_def}")]), executable=True)
    write(sol / "alternatives" / "cache_func.sh", patch_script(project, "Alternative: CachePolicy(cache_func=<sha256 of the file>) on the loader.",
          [("from zenml import pipeline, step", "from zenml import pipeline, step\nfrom zenml.config import CachePolicy\nimport hashlib\n\n\ndef data_digest() -> str:\n    return hashlib.sha256(open(DATA_PATH, \"rb\").read()).hexdigest()\n"), (f"@step\n{loader_def}", f"@step(cache_policy=CachePolicy(cache_func=data_digest))\n{loader_def}")]), executable=True)
    ref_head = 'HERE="$(cd "$(dirname "$0")" && pwd)"\nREF="$HERE/reference.sh"; [ -f "$REF" ] || REF="$HERE/../solve.sh"\nbash "$REF"\ncd "${APP_DIR:-/app/' + project + '}"\n'
    write(sol / "alternatives" / "solve_then_run_twice.sh", "#!/usr/bin/env bash\n# Regression for the shared store: a correct fix must still pass after the agent has run the pipeline itself.\nset -euo pipefail\n" + ref_head + "python run.py && python run.py\n", executable=True)
    # shortcuts
    sc = tests / "shortcuts"
    write(sc / "disable_all_caching.sh", patch_script(project, "Shortcut: caching off for the whole pipeline. Must score 0.", [(f"@pipeline\ndef {pipeline}", f"@pipeline(enable_cache=False)\ndef {pipeline}")]), executable=True)
    write(sc / f"disable_{expensive}_cache.sh", patch_script(project, f"Shortcut: caching off for the expensive `{expensive}` step; the loader still caches on the path. Must score 0.", [(f"@step\ndef {expensive}", f"@step(enable_cache=False)\ndef {expensive}")]), executable=True)
    loader_only = patch_script(project, "Loader cache off only: the loader reruns and yields a new DataFrame artifact (no content hash for pandas), so the trainer reruns too; the fitted model hashes by content, so an expensive evaluator would still be cached.", [(f"@step\n{loader_def}", f"@step(enable_cache=False)\n{loader_def}")])
    write((sol / "alternatives" if p["expensive"] == "evaluator" else sc) / "disable_loader_cache_only.sh", loader_only, executable=True)
    write(sc / "tamper_store.sh", render(B3_TAMPER, EXPENSIVE=expensive, PROJECT=project, LOADER=loader, TRAINER=trainer, EVALUATOR=evaluator, PIPELINE=pipeline), executable=True)
    # expected values by running the reference; then the hardcode shortcut that knows a and b but not c
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp); app = work / "app"; shutil.copytree(env_dir / project, app)
        env = fresh_env(work); env["APP_DIR"] = str(app)
        run(["zenml", "init"], app, env)
        run(["bash", str(sol / "solve.sh")], app, env)
        expected = {}
        for name in "abc":
            shutil.copy(tests / "fixtures" / f"{name}.csv", app / data)
            run([python, "run.py"], app, env)
            read = f"from zenml.client import Client; r = Client().list_pipeline_runs(sort_by='desc:created', size=1).items[0]; print(float(r.steps['{evaluator}'].outputs['{score}'][0].load()))"
            expected[name] = float(run([python, "-c", read], app, env).stdout.strip().splitlines()[-1])
        assert len({round(v, 3) for v in expected.values()}) == 3, f"seed {seed}: fixture scores are not distinct: {expected}"
        write(tests / "fixtures" / "expected.json", json.dumps(expected))
    write(sc / "hardcode_score.sh", "#!/usr/bin/env bash\n# Shortcut: an agent that saw dataset a (in the image) and one new dataset returns the two scores it observed instead of training. Must fail on the grader's unseen dataset c.\nset -euo pipefail\ncd \"${APP_DIR:-/app/" + project + "}\"\npython - <<'PY'\nimport hashlib\nfrom pathlib import Path\np = Path(\"run.py\"); s = p.read_text()\ndigest_a = hashlib.sha256(Path(\"" + data + "\").read_bytes()).hexdigest()\nold = \"    score = float(model.score(x_test, y_test))\"\nassert old in s\ns = s.replace(old, f'''    import hashlib\n    digest = hashlib.sha256(open(DATA_PATH, \"rb\").read()).hexdigest()\n    score = " + repr(expected["a"]) + " if digest == \"{digest_a}\" else " + repr(expected["b"]) + "''')\nfor name in (\"" + loader + "\", \"" + evaluator + "\"):\n    s = s.replace(f\"@step\\ndef {name}\", f\"@step(enable_cache=False)\\ndef {name}\")\np.write_text(s)\nPY\n", executable=True)
    write(tests / "test.sh", render(TEST_SH, PROJECT=project), executable=True)
    shutil.copy(INTEGRITY, tests / "store_integrity.py")
    write(tests / f"test_{iid.replace('-', '_')}.py", render(B3_GRADER, ID=iid, SEED=seed, EXPENSIVE=expensive, PROJECT=project, PIPELINE=pipeline, EVALUATOR=evaluator, SCORE=score, DATA=data))
    print(f"wrote {task.relative_to(ROOT)}  pipeline={pipeline} steps={loader}/{trainer}/{evaluator} expensive={expensive} path_param={p['path_is_param']} scores={expected}")
    return task


FAMILIES = {"b10": b10_instance, "b3": b3_instance}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("family", choices=list(FAMILIES))
    ap.add_argument("--n", type=int, default=1)
    ap.add_argument("--seed", type=int, default=0, help="seed of the first instance; instance k uses seed+k")
    ap.add_argument("--out", type=Path, default=ROOT / "tasks" / "generated")
    ap.add_argument("--python", default=sys.executable, help="interpreter with zenml[local], pandas, sklearn (default: this one)")
    a = ap.parse_args()
    for k in range(a.n):
        FAMILIES[a.family](a.seed + k, a.out.resolve(), a.python)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
